spring.application.name=student-management

server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5433/studentdb
spring.datasource.username=postgres
spring.datasource.password=Dhinesh7190

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
jwt.secret=MyVerySecretKeyForSpringBootJWTAuthentication123456780

logging.level.root=INFO
logging.level.com.dinesh.student_manager=DEBUG